### PR TITLE
Add The Setup feed as an example.

### PR DESCRIPTION
**Pull request by waferbaby**
Hey friend! I've added JSON Feeds to usesthis.com. Enjoy :)

### CODE REVIEW

**Comment by valtlai** [comment]
JSON strings can’t contain literal newlines. They must be escaped (`\n`).

**Comment by waferbaby** [comment]
@valtlai Ooh, right!

**Comment by waferbaby** [comment]
Aaaaaaand updated.

**Comment by waferbaby** [comment]
This still useful?

**Comment by waferbaby** [comment]
Yo! Should I close this one?

**Pull request closed without merging**
